// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiBUZyIdVC7gBTQSzEoDunUs7hzKxr66k',
    appId: '1:537831035265:web:ae60237018491189511880',
    messagingSenderId: '537831035265',
    projectId: 'boma-27b0f',
    authDomain: 'boma-27b0f.firebaseapp.com',
    storageBucket: 'boma-27b0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArQod6yl3whj2Ly9rlaNnk4GUe_bxtL6c',
    appId: '1:537831035265:android:88e863b75ea03635511880',
    messagingSenderId: '537831035265',
    projectId: 'boma-27b0f',
    storageBucket: 'boma-27b0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyComo6FgBO3QBj_LsetfLOLUasA0U2_BYk',
    appId: '1:537831035265:ios:bffeaf6f97f78442511880',
    messagingSenderId: '537831035265',
    projectId: 'boma-27b0f',
    storageBucket: 'boma-27b0f.appspot.com',
    iosClientId: '537831035265-78uefj5ndntovu666iloknj1cao9s5sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.boma',
  );
}
